# Generated by Django 4.2.1 on 2023-07-15 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0007_watchlist_avg_rating_watchlist_number_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streamplatform',
            name='about',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='streamplatform',
            name='name',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='streamplatform',
            name='website',
            field=models.URLField(max_length=128),
        ),
    ]
