# Generated by Django 4.2.1 on 2023-07-15 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0008_alter_streamplatform_about_alter_streamplatform_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='description',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
